language: ruby
sudo: false
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
  - ruby-head
  - jruby-head
gemfile: Gemfile.travis
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
